import json
import os
import ollama

# Point this to where the Edge Node saved the batch JSON
JSON_FILE_PATH = "../data/master_metadata_log.json"

def generate_auditor_report_prompt(json_path):
    if not os.path.exists(json_path):
        print(f"Error: Could not find {json_path}")
        return None

    with open(json_path, 'r') as f:
        data = json.load(f)

    # 1. Start building the prompt context
    prompt = f"""
Review the following automated Edge AI telemetry data and generate a concise Security Incident Report.

--- SYSTEM OVERVIEW ---
Total Videos Processed: {data.get('total_videos_processed', 0)}

--- CRITICAL INCIDENTS LOG ---
"""
    
    incident_count = 0

    # 2. Parse the JSON and filter for ONLY actionable intelligence
    for video in data.get('processed_videos', []):
        video_name = video.get('filename', 'Unknown')
        has_incidents = False
        video_log = f"\nVideo Source: {video_name}\n"

        for chunk in video.get('chunks', []):
            timestamp = f"00:00:{chunk['chunk_id'] // 2:02d}" 
            
            # Extract Suspicious Actions
            for track in chunk.get('tracking_data', []):
                if track['status'] == "SUSPICIOUS":
                    video_log += f"[{timestamp}] ALERT: ID {track['id']} flagged for '{track['action']}'.\n"
                    has_incidents = True
                    incident_count += 1
            
            # Extract Proximity Violations
            for alert in chunk.get('proximity_flags', []):
                video_log += f"[{timestamp}] PROXIMITY: {alert}\n"
                has_incidents = True
                incident_count += 1

        if has_incidents:
            prompt += video_log
            
    if incident_count == 0:
        prompt += "\nNo suspicious activity or proximity violations detected across the batch.\n"

    # 3. Add the final instructions for Gemma
    prompt += """
--- INSTRUCTIONS ---
Based on the log above, please provide:
1. An Executive Summary of the security posture.
2. A bulleted list of specific High-Risk Incidents (if any), referencing the IDs and actions.
3. Actionable recommendations for the branch manager.
"""
    return prompt

def run_local_gemma_audit():
    print("1. Parsing Edge Node JSON...")
    prompt = generate_auditor_report_prompt(JSON_FILE_PATH)
    
    if not prompt:
        return

    print("2. Booting Local Gemma Engine (Air-Gapped Processing)...")
    print("3. Generating Security Audit. Please wait...\n")
    print("=" * 50)
    
    # Send the prompt to the locally hosted Gemma model
    response = ollama.chat(model='gemma', messages=[
        {
            'role': 'system',
            'content': 'You are an expert Loss Prevention Auditor for a Gold Loan branch. You speak with authority, conciseness, and focus purely on physical security risks.'
        },
        {
            'role': 'user',
            'content': prompt
        }
    ])

    # Print the final report generated by the AI
    print(response['message']['content'])
    print("=" * 50)

if __name__ == "__main__":
    run_local_gemma_audit()