import ollama
import os

def generate_analytics_report():
    log_file_path = "../data/metadata_log.txt"
    print("Cloud Server (Local M4 Host): Ingesting Generic Metadata Log...")
    
    if not os.path.exists(log_file_path):
        print(f"Error: Log file not found at {log_file_path}")
        print("Please run the edge_pipeline.py script first to generate the log!")
        return

    with open(log_file_path, "r") as f:
        metadata_log = f.read()

    print("Cloud Server (Local M4 Host): Prompting Llama-3 for Scene Summary...")
    print("Notice: Running 100% locally on Apple Silicon. Zero network calls made.\n")
    
    # We change the persona to a generic Video Analytics Engine
    system_prompt = """
    You are an advanced AI Video Analytics Engine. 
    Your job is to read the timestamped Edge Metadata Log generated by a generic CCTV/webcam pipeline.
    
    Write a concise, professional 2-paragraph summary of the events in the video.
    1. Summarize the general flow of movement (when motion started/stopped).
    2. Describe the physical path the person took based on the LEFT, CENTER, and RIGHT zone tracking.
    3. Conclude with a brief sentence on whether the scene showed high activity or was mostly static.
    """

    user_data = f"""
    EDGE METADATA LOG:
    {metadata_log}
    """

    # Call the local Ollama instance running on your M4
    try:
        response = ollama.chat(model='llama3', messages=[
            {'role': 'system', 'content': system_prompt},
            {'role': 'user', 'content': user_data}
        ])
        
        report = response['message']['content']
        
        print("="*60)
        print("FINAL VIDEO ANALYTICS REPORT")
        print("="*60)
        print(report)
        print("="*60)
        
    except Exception as e:
        print(f"Error communicating with Ollama: {e}")
        print("Did you remember to run 'ollama run llama3' in your terminal first?")

if __name__ == "__main__":
    generate_analytics_report()